from models.commons.model.schema import ModelActions
from models.commons.testing.config import ActionTestCase, TestSuite, VariantTestMapping
from models.commons.testing.runner import _validate_log_prob, generate_tests_from_suite
from models.commons.testing.shared_assets import STANDARD_PROTEIN
from models.esm2.config import MODEL_FAMILY
from models.esm2.fixture import (
    MASKED_INPUT,
    MASKED_PREDICT_OUTPUT_TPL,
    MULTIPLE_ENCODE_OUTPUT_TPL,
    MULTIPLE_SEQS_INPUT,
    SINGLE_ENCODE_OUTPUT_TPL,
    SINGLE_SEQ_INPUT,
)
from models.esm2.schema import ESM2ModelSizes

# ESM2 test suite - multiple variants, multiple actions
test_suite = TestSuite(
    model_family=MODEL_FAMILY,
    r2_fixture_subdir="models",
    variant_test_mappings=[
        # Encode/predict golden comparison runs on three reference variants
        # (35m, 150m, 3b). Each variant has its own golden (embeddings/logits are
        # size-specific), generated by fixture.py. The remaining sizes (8m, 650m)
        # are covered by the log_prob case below (all variants) + the deployment
        # tests. Golden output filenames are per-variant via the {variant.name}
        # template (e.g. "35m_single_encode_expected_output.json").
        #
        # Tolerances mirror the sibling protein-LM encode/predict standard:
        # rel_tol=1e-4 gates scalar/int fields and the L2-norm magnitude ratio,
        # while cosine_distance_threshold=0.02 gates embedding/logit vector
        # direction (float nondeterminism across CPU/GPU kernels shifts magnitudes
        # slightly but preserves direction).
        VariantTestMapping(
            variant_config={"MODEL_SIZE": ESM2ModelSizes.SIZE_35M},
            test_cases=[
                # Encode action - single sequence
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=SINGLE_SEQ_INPUT,  # String path
                    expected_output_fixture=SINGLE_ENCODE_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Encode action - multiple sequences
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=MULTIPLE_SEQS_INPUT,  # String path
                    expected_output_fixture=MULTIPLE_ENCODE_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Predict action - masked sequence
                ActionTestCase(
                    action_name=ModelActions.PREDICT,
                    input_fixture=MASKED_INPUT,  # String path
                    expected_output_fixture=MASKED_PREDICT_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
            ],
        ),
        VariantTestMapping(
            variant_config={"MODEL_SIZE": ESM2ModelSizes.SIZE_150M},
            test_cases=[
                # Encode action - single sequence
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=SINGLE_SEQ_INPUT,  # String path
                    expected_output_fixture=SINGLE_ENCODE_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Encode action - multiple sequences
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=MULTIPLE_SEQS_INPUT,  # String path
                    expected_output_fixture=MULTIPLE_ENCODE_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Predict action - masked sequence
                ActionTestCase(
                    action_name=ModelActions.PREDICT,
                    input_fixture=MASKED_INPUT,  # String path
                    expected_output_fixture=MASKED_PREDICT_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
            ],
        ),
        VariantTestMapping(
            variant_config={"MODEL_SIZE": ESM2ModelSizes.SIZE_3B},
            test_cases=[
                # Encode action - single sequence
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=SINGLE_SEQ_INPUT,  # String path
                    expected_output_fixture=SINGLE_ENCODE_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Encode action - multiple sequences
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=MULTIPLE_SEQS_INPUT,  # String path
                    expected_output_fixture=MULTIPLE_ENCODE_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Predict action - masked sequence
                ActionTestCase(
                    action_name=ModelActions.PREDICT,
                    input_fixture=MASKED_INPUT,  # String path
                    expected_output_fixture=MASKED_PREDICT_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
            ],
        ),
        # log_prob is validator-based (no golden), so it runs on ALL variants
        # (8m, 35m, 150m, 650m, 3b).
        VariantTestMapping(
            variant_config={},  # Empty dict means applies to ALL variants
            test_cases=[
                ActionTestCase(
                    action_name=ModelActions.LOG_PROB,
                    # Programmatic input - create data on the fly
                    input_fixture={"items": [{"sequence": STANDARD_PROTEIN}]},
                    # Use shared validator from commons
                    validator=_validate_log_prob,
                ),
            ],
        ),
    ],
)

# Generate integration tests (marked with @pytest.mark.integration)
test_esm2_integration = generate_tests_from_suite(test_suite, test_type="integration")

# Generate deployment tests (marked with @pytest.mark.deployment)
test_esm2_deployment = generate_tests_from_suite(test_suite, test_type="deployment")

# Usage:
#   pytest models/esm2/test.py -m integration -n auto --no-cov -v -s  # integration only
#   pytest models/esm2/test.py -m deployment -n auto --no-cov -v -s   # deployment only
#   pytest models/esm2/test.py -n auto --no-cov -v -s                 # both
