from models.commons.model.schema import ModelActions
from models.commons.testing.config import ActionTestCase, TestSuite, VariantTestMapping
from models.commons.testing.runner import _validate_log_prob, generate_tests_from_suite
from models.e1.config import MODEL_FAMILY
from models.e1.fixture import (
    ENCODE_1_INPUT,
    ENCODE_1_OUTPUT_TPL,
    ENCODE_2_INPUT,
    ENCODE_2_OUTPUT_TPL,
    ENCODE_3_INPUT,
    ENCODE_3_OUTPUT_TPL,
    PREDICT_INPUT,
    PREDICT_OUTPUT_TPL,
)
from models.e1.schema import E1PredictLogProbRequest, E1PredictLogProbRequestItem

# E1 test suite - multiple actions, multiple test cases per action
test_suite = TestSuite(
    model_family=MODEL_FAMILY,
    r2_fixture_subdir="models",
    variant_test_mappings=[
        # Single mapping that applies to ALL variants
        VariantTestMapping(
            variant_config={},  # Empty dict means applies to ALL variants
            test_cases=[
                # Encode action - multiple test cases using files generated by FixtureGenerator
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=ENCODE_1_INPUT,
                    expected_output_fixture=ENCODE_1_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=ENCODE_2_INPUT,
                    expected_output_fixture=ENCODE_2_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Encode with context sequences (retrieval-augmented mode)
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=ENCODE_3_INPUT,
                    expected_output_fixture=ENCODE_3_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Predict action - uses file generated by FixtureGenerator
                ActionTestCase(
                    action_name=ModelActions.PREDICT,
                    input_fixture=PREDICT_INPUT,
                    expected_output_fixture=PREDICT_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Predict log prob action with programmatic input (no file generation needed)
                # Single sequence mode
                ActionTestCase(
                    action_name=ModelActions.LOG_PROB,
                    # Programmatic input - create data on the fly
                    input_fixture=E1PredictLogProbRequest(
                        items=[
                            E1PredictLogProbRequestItem(
                                sequence="TPSSKEMMSQALKATFSGFTKEQQRLGIPKDPRQWTETHVRDWVMWAVNEFSLKGVDFQKF"
                            )
                        ]
                    ),
                    # Use shared validator from commons
                    validator=_validate_log_prob,
                ),
                # Predict log prob with context sequences (retrieval-augmented mode)
                ActionTestCase(
                    action_name=ModelActions.LOG_PROB,
                    input_fixture=E1PredictLogProbRequest(
                        items=[
                            E1PredictLogProbRequestItem(
                                sequence="TPSSKEMMSQALKATFSGFTKEQQRLGIPKDPRQWTETHVRDWVMWAVNEFSLKGVDFQKF",
                                context_sequences=[
                                    "MPSSKEMMSQALKATFSGFTKEQQRLGIPKDPRQWTETHVRDWVMWAVNEFSLKGVDFQKL",
                                    "TPSSKELMSQALKATFSGFTKEQQRLGIPKDPRQWTETHVRDWVMWAVNEFSLKGVDFQKY",
                                ],
                            )
                        ]
                    ),
                    validator=_validate_log_prob,
                ),
            ],
        )
    ],
)


# Generate integration tests (marked with @pytest.mark.integration)
generate_tests_from_suite(test_suite, test_type="integration")

# Generate deployment tests (marked with @pytest.mark.deployment)
generate_tests_from_suite(test_suite, test_type="deployment")

# Usage:
#   pytest models/e1/test.py -m integration -n auto --no-cov -v -s  # integration only
#   pytest models/e1/test.py -m deployment -n auto --no-cov -v -s   # deployment only
#   pytest models/e1/test.py -n auto --no-cov -v -s                 # both
