from models.commons.model.schema import ModelActions
from models.commons.testing.config import ActionTestCase, TestSuite, VariantTestMapping
from models.commons.testing.runner import _validate_log_prob, generate_tests_from_suite
from models.commons.testing.shared_assets import STANDARD_PROTEIN
from models.esmc.config import MODEL_FAMILY
from models.esmc.fixture import (
    ENCODE_1_INPUT,
    ENCODE_1_OUTPUT_TPL,
    ENCODE_2_INPUT,
    ENCODE_2_OUTPUT_TPL,
    PREDICT_INPUT,
    PREDICT_OUTPUT_TPL,
)
from models.esmc.schema import ESMCPredictLogProbRequest, ESMCPredictLogProbRequestItem

# ESM-C test suite - multiple actions, multiple test cases per action
test_suite = TestSuite(
    model_family=MODEL_FAMILY,
    r2_fixture_subdir="models",
    variant_test_mappings=[
        # Single mapping — esmc ships the 300m variant only
        VariantTestMapping(
            variant_config={},  # Empty dict means applies to ALL variants
            test_cases=[
                # Encode action - multiple test cases using files generated by FixtureGenerator
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=ENCODE_1_INPUT,
                    expected_output_fixture=ENCODE_1_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                ActionTestCase(
                    action_name=ModelActions.ENCODE,
                    input_fixture=ENCODE_2_INPUT,
                    expected_output_fixture=ENCODE_2_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Predict action - uses file generated by FixtureGenerator
                ActionTestCase(
                    action_name=ModelActions.PREDICT,
                    input_fixture=PREDICT_INPUT,
                    expected_output_fixture=PREDICT_OUTPUT_TPL,
                    tolerances={"rel_tol": 1e-4, "cosine_distance_threshold": 0.02},
                ),
                # Predict log prob action with programmatic input (no file generation needed)
                ActionTestCase(
                    action_name=ModelActions.LOG_PROB,
                    # Programmatic input - create data on the fly
                    input_fixture=ESMCPredictLogProbRequest(
                        items=[ESMCPredictLogProbRequestItem(sequence=STANDARD_PROTEIN)]
                    ),
                    # Use shared validator from commons
                    validator=_validate_log_prob,
                ),
            ],
        )
    ],
)


# Generate integration tests (marked with @pytest.mark.integration)
test_esmc_integration = generate_tests_from_suite(test_suite, test_type="integration")

# Generate deployment tests (marked with @pytest.mark.deployment)
test_esmc_deployment = generate_tests_from_suite(test_suite, test_type="deployment")

# Usage:
#   pytest models/esmc/test.py -m integration -n auto --no-cov -v -s  # integration only
#   pytest models/esmc/test.py -m deployment -n auto --no-cov -v -s   # deployment only
#   pytest models/esmc/test.py -n auto --no-cov -v -s                 # both
